--NUMERI DI MATRICOLA

CREATE SEQUENCE MAT 
 START WITH 7000000
 INCREMENT BY 1;

--REATI COMMESSI

CREATE SEQUENCE OFF 
 START WITH 21
 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER SEQ_OFF
BEFORE INSERT ON OFFENSE
FOR EACH ROW
BEGIN
:NEW.OFFENSE_ID:=OFF.NEXTVAL;
END;

--PASS VISITATORI

CREATE SEQUENCE VIS 
 START WITH 16
 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER SEQ_VIS
BEFORE INSERT ON VISITOR
FOR EACH ROW
BEGIN
:NEW.PASS_NUMB:=VIS.NEXTVAL;
END;

--ESECUZIONI PROGRAMMATE

CREATE SEQUENCE SCH_KEY
START WITH 17
INCREMENT BY 1;

--ESECUZIONI EFFETTUATE

CREATE SEQUENCE EXC_KEY
START WITH 516
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER SEQ_EXC
BEFORE INSERT ON EXECUTED_EXEC
FOR EACH ROW
BEGIN
:NEW.EXEC_NUMBER:=EXC_KEY.NEXTVAL;
END;

--NUM. CARTELLINO AGENTI

CREATE SEQUENCE AGT
START WITH 16
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER SEQ_AGT
BEFORE INSERT ON AGENT
FOR EACH ROW
BEGIN
:NEW.CARD_NUMBER:=AGT.NEXTVAL;
END;
