DROP TABLE IN_PRES_OF;
DROP TABLE WITNESS;
DROP TABLE EXECUTED_EXEC;
DROP TABLE SCHED_EXEC;
DROP TABLE MONITOR;
DROP TABLE TURN;
DROP TABLE AGENT;
DROP TABLE PLACED;
DROP TABLE CELL;
DROP TABLE SECTION;
DROP TABLE PROTECT;
DROP TABLE WITH_VIS;
DROP TABLE VISITOR;
DROP TABLE VISIT;
DROP TABLE VICTIM;
DROP TABLE CRIMINAL_HOMICIDE;
DROP TABLE COMMITTED;
DROP TABLE OFFENSE;
DROP TABLE REGISTRATION;
DROP TABLE LAWYER;
DROP TABLE OFFENDER;
DROP TABLE PERSON;



CREATE TABLE PERSON(
SSN CHAR(9),
NAME VARCHAR2(15) NOT NULL,
SURNAME VARCHAR2(15) NOT NULL,
BDATE DATE,
SEX CHAR(1) CHECK(UPPER(SEX)='M' OR UPPER(SEX)='W'),
TELEPHONE VARCHAR2(15),
STREET VARCHAR2(15),
COUNTY VARCHAR2(10),
CONSTRAINT PERSON_PK PRIMARY KEY(SSN));

CREATE TABLE OFFENDER(
OFFENDER_SSN CHAR(9),
NATIVE_COUNTY VARCHAR2(10) NOT NULL,
EYE_COLOR VARCHAR2(10) NOT NULL,
HAIR_COLOR VARCHAR2(10) NOT NULL,
EDUC_LEV NUMBER(2) CHECK(EDUC_LEV>0 AND EDUC_LEV<13),
RACE VARCHAR2(10) NOT NULL CHECK(UPPER(RACE) IN('WHITE','BLACK','HISPANIC','OTHER')),
CONSTRAINT OFFENDER_PK PRIMARY KEY(OFFENDER_SSN),
CONSTRAINT OFFENDER_FK FOREIGN KEY(OFFENDER_SSN) REFERENCES PERSON(SSN));

CREATE TABLE LAWYER(
LAWYER_SSN CHAR(9),
BAR_CARD_NUMBER CHAR(8) UNIQUE NOT NULL,
INT_EXT CHAR(1) CHECK(UPPER(INT_EXT)='I' OR UPPER(INT_EXT)='E') NOT NULL,
WEBSITE VARCHAR2(30),
LICENSE_DATE DATE NOT NULL,
CONSTRAINT LAWYER_PK PRIMARY KEY(LAWYER_SSN),
CONSTRAINT LAWYER_FK FOREIGN KEY(LAWYER_SSN) REFERENCES PERSON(SSN));

CREATE TABLE REGISTRATION(
REG_NUMBER NUMBER(7),
OFF_SSN CHAR(9) NOT NULL,
DATE_REC DATE NOT NULL,
MEASURED_H CHAR(5) NOT NULL,
MEASURED_W NUMBER(3) NOT NULL CHECK(MEASURED_W>0),
SENTENCE CHAR(3) CHECK(UPPER(SENTENCE) IN('STD','LFT','DRW')) NOT NULL,
RELEASE_DATE DATE,
CONSTRAINT REGISTRATION_PK PRIMARY KEY(REG_NUMBER),
CONSTRAINT REGISTRATION_FK FOREIGN KEY(OFF_SSN) REFERENCES OFFENDER(OFFENDER_SSN));
ALTER TABLE REGISTRATION ADD CONSTRAINT CK1 CHECK(RELEASE_DATE>DATE_REC);

CREATE TABLE OFFENSE(
OFFENSE_ID NUMBER(10) CHECK(OFFENSE_ID>0),
OFFENSE_TYPE VARCHAR2(10) NOT NULL,
DATE_OFF DATE,
COUNTY VARCHAR2(10),
CONSTRAINT OFFENSE_PK PRIMARY KEY(OFFENSE_ID));

CREATE TABLE COMMITTED(
REG_NUM NUMBER(7,0),
OFFENSE_ID NUMBER(10),
ROLE VARCHAR2(10),
YEARS_S NUMBER(2) CHECK(YEARS_S>0),
MONTHS_S NUMBER(2) CHECK(MONTHS_S>0),
DAYS_S NUMBER(3) CHECK(DAYS_S>0),
CONSTRAINT COMMITTED_PK PRIMARY KEY(REG_NUM,OFFENSE_ID),
CONSTRAINT COMMITTED_FK FOREIGN KEY(REG_NUM) REFERENCES REGISTRATION(REG_NUMBER),
CONSTRAINT COMMITTED_FK2 FOREIGN KEY(OFFENSE_ID) REFERENCES OFFENSE(OFFENSE_ID));

CREATE TABLE CRIMINAL_HOMICIDE(
HOMICIDE_ID NUMBER(10),
USED_WEAPON VARCHAR2(15),
HOMICIDE_TYPE VARCHAR2(4) NOT NULL CHECK(UPPER(HOMICIDE_TYPE) IN('CMDR','MDR','MLR','CNH')),
NUMB_VICTIMS NUMBER(2),
CONSTRAINT HOMICIDE_PK PRIMARY KEY(HOMICIDE_ID),
CONSTRAINT HOMICIDE_FK FOREIGN KEY(HOMICIDE_ID) REFERENCES OFFENSE(OFFENSE_ID));

CREATE TABLE VICTIM(
VICTIM_SSN CHAR(9),
HOM_ID NUMBER(10) NOT NULL,
RACE VARCHAR2(10) NOT NULL CHECK(UPPER(RACE) IN('WHITE','BLACK','HISPANIC','OTHER')),
CONSTRAINT VICTIM_PK PRIMARY KEY(VICTIM_SSN),
CONSTRAINT VICTIM_FK FOREIGN KEY(VICTIM_SSN) REFERENCES PERSON(SSN),
CONSTRAINT VICTIM_FK2 FOREIGN KEY(HOM_ID) REFERENCES CRIMINAL_HOMICIDE(HOMICIDE_ID));

CREATE TABLE VISIT(
REG_NUM NUMBER(7),
VISIT_DYHR DATE,
END_HOUR DATE NOT NULL,
CONSTRAINT VISIT_PK PRIMARY KEY(REG_NUM,VISIT_DYHR),
CONSTRAINT VISIT_FK FOREIGN KEY(REG_NUM) REFERENCES REGISTRATION(REG_NUMBER));
ALTER TABLE VISIT ADD CONSTRAINT CON2 CHECK(END_HOUR>VISIT_DYHR AND VISIT_DYHR+1/24>=END_HOUR); [DURATA MASSIMA COLLOQUIO:1H]

CREATE TABLE VISITOR(
VISITOR_SSN CHAR(9),
PASS_NUMB NUMBER(5) NOT NULL UNIQUE CHECK(PASS_NUMB>0),
CONSTRAINT VISITOR_PK PRIMARY KEY(VISITOR_SSN),
CONSTRAINT VISITOR_FK FOREIGN KEY(VISITOR_SSN) REFERENCES PERSON(SSN));

CREATE TABLE WITH_VIS(
REG_NUM NUMBER(7),
VISIT_DATE DATE,
VISITOR_SSN CHAR(9),
CONSTRAINT WITH_PK PRIMARY KEY(REG_NUM,VISIT_DATE,VISITOR_SSN),
CONSTRAINT WITH_FK FOREIGN KEY(REG_NUM,VISIT_DATE) REFERENCES VISIT(REG_NUM,VISIT_DYHR) ON DELETE CASCADE, 
CONSTRAINT WITH_FK2 FOREIGN KEY(VISITOR_SSN) REFERENCES VISITOR(VISITOR_SSN));

CREATE TABLE PROTECT(
LAWYER_SSN CHAR(9) NOT NULL,
REG_NUM NUMBER(7),
START_DATE DATE,
END_DATE DATE,
CONSTRAINT PROTECT_PK PRIMARY KEY(REG_NUM,START_DATE),
CONSTRAINT PROTECT_FK FOREIGN KEY(LAWYER_SSN) REFERENCES LAWYER(LAWYER_SSN),
CONSTRAINT PROTECT_FK2 FOREIGN KEY(REG_NUM) REFERENCES REGISTRATION(REG_NUMBER));
ALTER TABLE PROTECT ADD CONSTRAINT CON3 CHECK
(START_DATE=TRUNC(START_DATE) AND END_DATE=TRUNC(END_DATE) AND END_DATE>START_DATE);

CREATE TABLE SECTION(
CUSTODY_LEVEL_HOUSED VARCHAR2(4) CHECK(UPPER(CUSTODY_LEVEL_HOUSED) IN('STD','ADMS','DRW')),
CELL_SEATS NUMBER(1) NOT NULL CHECK(CELL_SEATS>0 AND CELL_SEATS<5),
CONSTRAINT SECTION_PK PRIMARY KEY(CUSTODY_LEVEL_HOUSED));

CREATE TABLE CELL(
CLH VARCHAR2(4),
CELL_NUM NUMBER(4) CHECK(CELL_NUM>0 AND CELL_NUM<=1500),
FREE_SEATS NUMBER(1) NOT NULL CHECK(FREE_SEATS>=0),
CONSTRAINT CELL_PK PRIMARY KEY(CLH,CELL_NUM),
CONSTRAINT CELL_FK FOREIGN KEY(CLH) REFERENCES SECTION(CUSTODY_LEVEL_HOUSED));

CREATE TABLE PLACED(
REG_NUM NUMBER(7),
CLH VARCHAR2(4) NOT NULL,
CELL_NUM NUMBER(4) NOT NULL,
START_DATE DATE,
END_DATE DATE,
CONSTRAINT PLACED_PK PRIMARY KEY(REG_NUM,START_DATE),
CONSTRAINT PLACED_FK FOREIGN KEY(REG_NUM) REFERENCES REGISTRATION(REG_NUMBER),
CONSTRAINT PLACED_FK2 FOREIGN KEY(CLH,CELL_NUM) REFERENCES CELL(CLH,CELL_NUM));
ALTER TABLE PLACED ADD CONSTRAINT CON4 CHECK(END_DATE>START_DATE);

CREATE TABLE AGENT(
AGENT_SSN CHAR(9),
CARD_NUMBER NUMBER(6) UNIQUE NOT NULL CHECK(CARD_NUMBER>0),
CONSTRAINT AGENT_PK PRIMARY KEY(AGENT_SSN),
CONSTRAINT AGENT_FK FOREIGN KEY(AGENT_SSN) REFERENCES PERSON(SSN));

CREATE TABLE TURN(
TURN_ID NUMBER(1) CHECK(TURN_ID>0),
START_HOUR DATE NOT NULL UNIQUE,
END_HOUR DATE NOT NULL UNIQUE,
CONSTRAINT TURN_PK PRIMARY KEY(TURN_ID));
ALTER TABLE TURN ADD CONSTRAINT CON5 CHECK(END_HOUR>START_HOUR);

CREATE TABLE MONITOR(
AGENT_SSN CHAR(9),
TURN_ID NUMBER(1) NOT NULL,
CLH VARCHAR2(4) NOT NULL,
DATE_TURN DATE,
CONSTRAINT MONITOR_PK PRIMARY KEY(AGENT_SSN,DATE_TURN),
CONSTRAINT MONITOR_FK FOREIGN KEY(AGENT_SSN) REFERENCES AGENT(AGENT_SSN),
CONSTRAINT MONITOR_FK2 FOREIGN KEY(CLH) REFERENCES SECTION(CUSTODY_LEVEL_HOUSED),
CONSTRAINT MONITOR_FK3 FOREIGN KEY(TURN_ID) REFERENCES TURN(TURN_ID));
ALTER TABLE MONITOR ADD CONSTRAINT DATE_CK CHECK(DATE_TURN=TRUNC(DATE_TURN));

CREATE TABLE SCHED_EXEC(
SCHED_EXEC_ID NUMBER(4) CHECK(SCHED_EXEC_ID>0),
REG_NUM NUMBER(7) NOT NULL UNIQUE,
DATE_EXEC DATE NOT NULL UNIQUE,
EXECUTION_TYPE VARCHAR2(20) CHECK(UPPER(EXECUTION_TYPE) IN('LETHAL INJECTION','ELECTROCUTION','LETHAL GAS','HANGING','FIRING SQUAD')) NOT NULL,
CONSTRAINT SCHED_EXEC_PK PRIMARY KEY(SCHED_EXEC_ID),
CONSTRAINT SCHED_EXEC_FK FOREIGN KEY(REG_NUM) REFERENCES REGISTRATION(REG_NUMBER));

CREATE TABLE EXECUTED_EXEC(
EXEC_NUMBER NUMBER(4),
SCHED_EXEC_ID NUMBER(4) NOT NULL UNIQUE,
START_HOUR DATE NOT NULL,
DEATH_HOUR DATE NOT NULL,
CONSTRAINT EXECUTED_EXEC_PK PRIMARY KEY(EXEC_NUMBER),
CONSTRAINT EXECUTED_EXEC_FK FOREIGN KEY(SCHED_EXEC_ID) REFERENCES SCHED_EXEC(SCHED_EXEC_ID));
ALTER TABLE EXECUTED_EXEC ADD CONSTRAINT CON7 CHECK(DEATH_HOUR>START_HOUR);

CREATE TABLE WITNESS(
WITNESS_SSN CHAR(9),
WITNESS_TYPE VARCHAR2(15) NOT NULL CHECK(UPPER(WITNESS_TYPE) IN('OFFENDER FAM','VICTIM FAM','MEDIA')),
PRESS_OFFICE_NAME VARCHAR2(20),
CONSTRAINT WITNESS_PK PRIMARY KEY(WITNESS_SSN),
CONSTRAINT WITNESS_FK FOREIGN KEY(WITNESS_SSN) REFERENCES PERSON(SSN));

CREATE TABLE IN_PRES_OF(
EXEC_NUMBER NUMBER(4),
WITNESS_SSN CHAR(9),
CONSTRAINT IN_PRES_OF_PK PRIMARY KEY(EXEC_NUMBER,WITNESS_SSN),
CONSTRAINT IN_PRES_OF_FK FOREIGN KEY(EXEC_NUMBER) REFERENCES EXECUTED_EXEC(EXEC_NUMBER),
CONSTRAINT IN_PRES_OF_FK2 FOREIGN KEY(WITNESS_SSN) REFERENCES WITNESS(WITNESS_SSN));
