/*Questo trigger si attiva prima dell'inserimento di un'esecuzione prevista.Controlla che il
condannato si trovi effettivamente in carcere,che la data di esecuzione sia successiva alla data di
immatricolazione e che il detenuto sia effettivamente condannato alla pena capitale.*/

CREATE OR REPLACE TRIGGER T_SCHEDEXEC
BEFORE INSERT ON SCHED_EXEC
FOR EACH ROW
DECLARE
	ROW_R REGISTRATION%ROWTYPE;
	CNT1 NUMBER;
	EXC1 EXCEPTION;
	EXC2 EXCEPTION;
BEGIN
	SELECT * INTO ROW_R FROM OFFENDER_IN WHERE REG_NUMBER=:NEW.REG_NUM; 
	IF(ROW_R.SENTENCE<>'DRW') THEN
		RAISE EXC1;
	END IF;
	IF(:NEW.DATE_EXEC<ROW_R.DATE_REC) THEN
		RAISE EXC2;
	END IF;
	:NEW.SCHED_EXEC_ID:=SCH_KEY.NEXTVAL;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
	RAISE_APPLICATION_ERROR(-20001,'OFFENDER INEXISTENT/NOT PRESENT');
	WHEN EXC1 THEN
	RAISE_APPLICATION_ERROR(-20002,'OFFENDER NOT SENTENCES TO DEATH');
	WHEN EXC2 THEN
	RAISE_APPLICATION_ERROR(-20003,'OFFENDER '||:NEW.REG_NUM||' NOT WAS REGISTERED IN DATE '||:NEW.DATE_EXEC);
END;