/*Questo trigger si attiva prima dell'inserimento di un colloquio.Controlla dapprima che la data del
colloquio sia successiva alla data dell’immatricolazione e infine verifica se vi sono stati altri colloqui
tenuti dal detenuto nella settimana in corso,in quanto e' previsto al piu' un colloquio settimanale
per ogni detenuto della durata massima di 1h.*/

CREATE OR REPLACE TRIGGER T_VISIT
BEFORE INSERT ON VISIT
FOR EACH ROW
DECLARE
	COUNTER NUMBER;
	DATE_R DATE;
	CLEVEL VARCHAR2(4);
	EXC1 EXCEPTION;
	EXC2 EXCEPTION;
	EXC3 EXCEPTION;
	DAY_I CHAR(3);
BEGIN
	SELECT DATE_REC INTO DATE_R FROM OFFENDER_IN WHERE REG_NUMBER=:NEW.REG_NUM;
	IF(TRUNC(:NEW.VISIT_DYHR)<TRUNC(DATE_R)) THEN
		RAISE EXC1;
	END IF;
	SELECT COUNT(*) INTO COUNTER FROM VISIT
	WHERE REG_NUM=:NEW.REG_NUM AND TO_CHAR(VISIT_DYHR,'IW-YYYY')=TO_CHAR(:NEW.VISIT_DYHR,'IW-YYYY');
	IF COUNTER>0 THEN
		RAISE EXC2;
	END IF;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
	RAISE_APPLICATION_ERROR(-20001,'OFFENDER NOT IN PRISON ACTUALLY');
	WHEN EXC1 THEN
	RAISE_APPLICATION_ERROR(-20003,'OFFENDER '||:NEW.REG_NUM||' NOT WAS REGISTERED IN DATE '||:NEW.VISIT_DYHR);
	WHEN EXC2 THEN
	RAISE_APPLICATION_ERROR(-20003,'ANOTHER VISIT IN THIS WEEK FOR OFFENDER N.'||:NEW.REG_NUM);
END;