/*Questo trigger impedisce che ad un colloquio siano presenti piu’ di tre persone adulte ed un
minorenne.*/

CREATE OR REPLACE TRIGGER T_WITH
BEFORE INSERT ON WITH_VIS
FOR EACH ROW
DECLARE
	AGE NUMBER;
	BD DATE;
	COUNTER NUMBER;
	EXC1 EXCEPTION;
	EXC2 EXCEPTION;
BEGIN
	SELECT BDATE INTO BD FROM PERSON WHERE SSN=:NEW.VISITOR_SSN;
	SELECT FLOOR(MONTHS_BETWEEN(:NEW.VISIT_DATE,BD)/12) INTO AGE FROM DUAL;
	IF AGE>=18 THEN
		SELECT COUNT(*) INTO COUNTER FROM WITH_VIS W JOIN PERSON P ON W.VISITOR_SSN=P.SSN
		WHERE REG_NUM=:NEW.REG_NUM AND VISIT_DATE=:NEW.VISIT_DATE AND 
		FLOOR(MONTHS_BETWEEN(:NEW.VISIT_DATE,BDATE)/12)>=18;
		IF COUNTER=3 THEN
			RAISE EXC1;
		END IF;
	ELSE
		SELECT COUNT(*) INTO COUNTER FROM WITH_VIS W JOIN PERSON P ON W.VISITOR_SSN=P.SSN
		WHERE REG_NUM=:NEW.REG_NUM AND VISIT_DATE=:NEW.VISIT_DATE AND 
		FLOOR(MONTHS_BETWEEN(:NEW.VISIT_DATE,BDATE)/12)<18;
		IF COUNTER=1 THEN
			RAISE EXC2;
		END IF;
	END IF;
EXCEPTION
	WHEN EXC1 THEN
	RAISE_APPLICATION_ERROR(-20001,'TOO MANY ADULTS FOR VISIT:'||:NEW.VISIT_DATE||' OFFENDER:'||:NEW.REG_NUM);
	WHEN EXC2 THEN
	RAISE_APPLICATION_ERROR(-20002,'TOO MANY CHILDRENS FOR VISIT:'||:NEW.VISIT_DATE||' OFFENDER:'||:NEW.REG_NUM);
END;