/*Questo trigger controlla che ad ogni esecuzione non siano presenti piu’ di 5 testimoni appartenenti
alla famiglia del condannato,5 appartenenti alla famiglia della vittima e 4 appartenenti ai media.*/

CREATE OR REPLACE TRIGGER T_WITNESS
BEFORE INSERT ON IN_PRES_OF
FOR EACH ROW
DECLARE
	W_TYPE VARCHAR2(15);
	MAX_W NUMBER;
	COUNTER NUMBER;
	EXC1 EXCEPTION;
BEGIN
	SELECT WITNESS_TYPE INTO W_TYPE FROM WITNESS
	WHERE WITNESS_SSN=:NEW.WITNESS_SSN;
	IF W_TYPE='OFFENDER FAM' OR W_TYPE='VICTIM FAM' THEN
		MAX_W:=5;
	ELSE
		MAX_W:=4;
	END IF;
	SELECT COUNT(*) INTO COUNTER FROM IN_PRES_OF I JOIN WITNESS W ON I.WITNESS_SSN=W.WITNESS_SSN
	WHERE EXEC_NUMBER=:NEW.EXEC_NUMBER AND WITNESS_TYPE=W_TYPE;
	IF COUNTER=MAX_W THEN
		RAISE EXC1;
	END IF;
EXCEPTION
	WHEN EXC1 THEN
	RAISE_APPLICATION_ERROR(-20001,'TOO MANY '||W_TYPE||' FOR EXECUTION '||:NEW.EXEC_NUMBER);
END;




