--AMMINISTRATORE
CREATE USER ADMINISTRATOR IDENTIFIED BY ADM_PSW;
GRANT ALL PRIVILEGES TO ADMINISTRATOR;

--DIRETTORE
CREATE USER DIRECTOR IDENTIFIED BY DIR_PSW;
GRANT CREATE SESSION TO DIRECTOR;
GRANT EXECUTE ON CHANGE_SENTENCE TO DIRECTOR;
GRANT EXECUTE ON SET_EXEC TO DIRECTOR;
GRANT SELECT ON MY_VIEW TO DIRECTOR;
GRANT SELECT ON MY_VIEW2 TO DIRECTOR;
GRANT SELECT ON MY_VIEW3 TO DIRECTOR;
GRANT SELECT ON AGENT TO DIRECTOR;
GRANT SELECT ON CELL TO DIRECTOR;
GRANT SELECT ON COMMITTED TO DIRECTOR;
GRANT SELECT ON CRIMINAL_HOMICIDE TO DIRECTOR;
GRANT SELECT ON EXECUTED_EXEC TO DIRECTOR;
GRANT SELECT ON IN_PRES_OF TO DIRECTOR;
GRANT SELECT ON LAWYER TO DIRECTOR;
GRANT SELECT ON MONITOR TO DIRECTOR;
GRANT SELECT ON OFFENDER TO DIRECTOR;
GRANT SELECT ON OFFENSE TO DIRECTOR;
GRANT SELECT ON PERSON TO DIRECTOR;
GRANT SELECT ON PLACED TO DIRECTOR;
GRANT SELECT ON PROTECT TO DIRECTOR;
GRANT SELECT ON REGISTRATION TO DIRECTOR;
GRANT SELECT ON SCHED_EXEC TO DIRECTOR;
GRANT SELECT ON SECTION TO DIRECTOR;
GRANT SELECT ON TURN TO DIRECTOR;
GRANT SELECT ON VICTIM TO DIRECTOR;
GRANT SELECT ON VISIT TO DIRECTOR;
GRANT SELECT ON VISITOR TO DIRECTOR;
GRANT SELECT ON WITH_VIS TO DIRECTOR;
GRANT SELECT ON WITNESS TO DIRECTOR;

--IMPIEGATO
CREATE USER EMPLOYEE IDENTIFIED BY EMP_PSW;
GRANT CREATE SESSION TO EMPLOYEE;
GRANT EXECUTE CHANGE_CELL TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON PERSON TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON AGENT TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON COMMITTED TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON CRIMINAL_HOMICIDE TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON EXECUTED_EXEC TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON IN_PRES_OF TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON LAWYER TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON MONITOR TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON PERSON TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON OFFENDER TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON OFFENSE TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON PERSON TO EMPLOYEE;
GRANT SELECT ON PLACED TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON PROTECT TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON REGISTRATION TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON SCHED_EXEC TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON TURN TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON VICTIM TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON VISIT TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON VISITOR TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON WITH_VIS TO EMPLOYEE;
GRANT SELECT,INSERT,UPDATE,DELETE ON WITNESS TO EMPLOYEE;

--UTENTE
CREATE USER EXTERN_USR IDENTIFIED BY EXT_PSW;
GRANT CREATE SESSION TO EXTERN_USR;
GRANT SELECT ON MY_VIEW TO EXTERN_USR;
GRANT SELECT ON MY_VIEW2 TO EXTERN_USR;
GRANT SELECT ON MY_VIEW3 TO EXTERN_USR;
GRANT SELECT ON COMMITTED TO EXTERN_USR;
GRANT SELECT ON CRIMINAL_HOMICIDE TO EXTERN_USR;
GRANT SELECT ON EXECUTED_EXEC TO EXTERN_USR;
GRANT SELECT ON IN_PRES_OF TO EXTERN_USR;
GRANT SELECT ON OFFENDER TO EXTERN_USR;
GRANT SELECT ON OFFENSE TO EXTERN_USR;
GRANT SELECT ON PERSON TO EXTERN_USR;
GRANT SELECT ON REGISTRATION TO EXTERN_USR;
GRANT SELECT ON SCHED_EXEC TO EXTERN_USR;
GRANT SELECT ON WITH_VIS TO EXTERN_USR;
GRANT SELECT ON WITNESS TO EXTERN_USR;





