--INFORMAZIONI STATISTICHE RELATIVE ALLE ESECUZIONI EFFETTUATE

CREATE VIEW MY_VIEW AS
SELECT RACE,SEX,COUNT(*) TOT FROM (((EXECUTED_EXEC E JOIN SCHED_EXEC S ON E.SCHED_EXEC_ID=S.SCHED_EXEC_ID) JOIN REGISTRATION R ON S.REG_NUM=R.REG_NUMBER)
JOIN OFFENDER O ON R.OFF_SSN=O.OFFENDER_SSN) JOIN PERSON P ON O.OFFENDER_SSN=P.SSN
GROUP BY RACE,SEX;

SELECT RACE,SEX,TOT,ROUND((TOT/(SELECT SUM(TOT) FROM MY_VIEW)*100),2) AS PERCENTAGE FROM MY_VIEW;

/*Mediante la vista MY_VIEW ottengo informazioni statistiche relative alle esecuzioni
effettuate,mostrando per ogni combinazione [razza,sesso] il numero di esecuzioni effettuate.Tramite
l'interrogazione successiva visualizzo anche la percentuale di ogni combinazione sul totale delle
esecuzioni effettuate.*/

CREATE VIEW MY_VIEW3 AS
SELECT RACE,TO_CHAR(DATE_EXEC,'YYYY') YEAR,COUNT(*) TOT FROM (((EXECUTED_EXEC E JOIN SCHED_EXEC S ON E.SCHED_EXEC_ID=S.SCHED_EXEC_ID) JOIN REGISTRATION R ON S.REG_NUM=R.REG_NUMBER)
JOIN OFFENDER O ON R.OFF_SSN=O.OFFENDER_SSN) JOIN PERSON P ON O.OFFENDER_SSN=P.SSN
GROUP BY RACE,TO_CHAR(DATE_EXEC,'YYYY')
ORDER BY YEAR DESC;

SELECT RACE,YEAR,TOT,ROUND((TOT/(SELECT SUM(TOT) FROM MY_VIEW3 M3 WHERE M3.YEAR=M2.YEAR)*100),2) AS YEAR_PERCENTAGE
FROM MY_VIEW3 M2;

/*Mediante la vista MY_VIEW3 ottengo per ogni combinazione [razza,anno] il numero di esecuzioni
effettuate.Con l'interrogazione successiva visualizzo la percentuale annua di esecuzioni per razza.*/

--DETENUTI ATTUALMENTE IN CARCERE

CREATE VIEW OFFENDER_IN AS
 SELECT * FROM REGISTRATION WHERE RELEASE_DATE IS NULL;

/*TALE VISTA,AL FINE DI RENDERE MENO ONEROSE LE QUERY CHE NE FANNO USO,CONSIDERANDO CHE LA RELAZIONE
REGISTRATION CONTIENE I DATI DI TUTTE LE IMMATRICOLAZIONI ATTUALI E PASSATE,SI POTREBBE RENDERE MATERIALIZZATA.
LA VISTA DOVREBBE AGGIORNARSI AUTOMATICAMENTE AD OGNI OPERAZIONE DML SULLA BASE TABLE REGISTRATION (MEDIANTE
UN MATERIALIZED LOG SU TALE RELAZIONE EVITO DI DOVER RIGENERARE TOTALMENTE LA VISTA OGNI VOLTA,FAST REFRESH).
TALE SOLUZIONE NON E' STATA ADOTTATA A CAUSA DELLE LIMITAZIONI SOFTWARE DI ORACLE DATABASE CHE NELLA
VERSIONE EXPRESS NON CONSENTE TALE FUNZIONALITA' (ADVANCED REPLICATION,PRESENTE INVECE NELLA EE DI ORACLE).*/

--ELENCO DELLE ESECUZIONI PROGRAMMATE FUTURE

CREATE VIEW MY_VIEW2 AS
SELECT * FROM SCHED_EXEC WHERE DATE_EXEC>SYSDATE ORDER BY DATE_EXEC ASC;
