/*Questa funzione prende in input una sezione e restituisce in output il numero della prima cella
libera in tale sezione.*/

CREATE OR REPLACE FUNCTION GET_FREE_CELL(CUSTODY_LEV VARCHAR2) RETURN NUMBER
 IS
 NUM_C NUMBER;
 BEGIN
 	SELECT CELL_NUM INTO NUM_C FROM CELL  
 	WHERE (CLH=CUSTODY_LEV AND FREE_SEATS>0 AND ROWNUM=1);
 	RETURN NUM_C;
 EXCEPTION
 	WHEN NO_DATA_FOUND THEN
 	RAISE_APPLICATION_ERROR('-20010','NO AVAILABLE CELLS IN SECTION '|| CUSTODY_LEV);
 END GET_FREE_CELL;