/*Questa procedura condanna a morte e fissa un'esecuzione (del tipo ricevuto in input) nella prima
data disponibile a partire da 10 anni dalla data di esecuzione della procedura,a tutti i detenuti che
si trovano in carcere e che hanno compiuto almeno un reato nella contea ricevuta in
input,causando almeno il numero di vittime ricevuto in input in tale reato.Nel caso in cui il
detenuto sia condannato a morte ed abbia gia' programmata un'esecuzione questa non verra'
sovrascritta.Se il detenuto invece non e' condannato a morte viene chiamata la procedura
change_sentence che cambiera' la condanna,spostera’ il detenuto in una cella della sezione
'DRW',se disponibile, e poi fissera' l’esecuzione.*/

CREATE OR REPLACE PROCEDURE SET_EXEC(COUNTY_O VARCHAR2,NUM BINARY_INTEGER,TYPE VARCHAR2) IS
COUNTER NUMBER:=0;
COUNTER2 NUMBER;
SENTENCE_T VARCHAR2(4);
DATE_EX DATE:=ADD_MONTHS(SYSDATE,120);
BEGIN
	FOR MAT_CUR IN(SELECT DISTINCT REG_NUM FROM (OFFENSE O JOIN COMMITTED C ON O.OFFENSE_ID=C.OFFENSE_ID)JOIN CRIMINAL_HOMICIDE CH ON O.OFFENSE_ID=CH.HOMICIDE_ID
	WHERE EXISTS(SELECT * FROM OFFENDER_IN WHERE REG_NUMBER=C.REG_NUM) AND UPPER(COUNTY)=UPPER(COUNTY_O) AND NUMB_VICTIMS>=NUM) LOOP
		DBMS_OUTPUT.PUT_LINE('OFFENDER FOUND:'||MAT_CUR.REG_NUM);
		SELECT SENTENCE INTO SENTENCE_T FROM REGISTRATION WHERE REG_NUMBER=MAT_CUR.REG_NUM;
		IF SENTENCE_T='DRW' THEN
			SELECT COUNT(*) INTO COUNTER2 FROM SCHED_EXEC WHERE REG_NUM=MAT_CUR.REG_NUM;
			IF COUNTER2>0 THEN
				DBMS_OUTPUT.PUT_LINE('OFFENDER '||MAT_CUR.REG_NUM||' HAS ANOTHER SCHEDULED EXECUTION.NOTHING TO DO.');
				GOTO mybranch;
			END IF;
		ELSE
			CHANGE_SENTENCE(MAT_CUR.REG_NUM,'DRW',SYSDATE);
		END IF;
		FREE_DATE(DATE_EX);
		INSERT INTO SCHED_EXEC VALUES(NULL,MAT_CUR.REG_NUM,DATE_EX,UPPER(TYPE));
		COMMIT;
		DBMS_OUTPUT.PUT_LINE('SCHEDULED EXECUTION IN DATE:'||DATE_EX||' FOR THE OFFENDER N.'||MAT_CUR.REG_NUM);
		DATE_EX:=DATE_EX+1;
		<<mybranch>>
		COUNTER:=COUNTER+1;
	END LOOP;
	IF COUNTER=0 THEN
		DBMS_OUTPUT.PUT_LINE('NO OFFENDER,ACTUALLY IN PRISON,HAS COMMITTED AN OFFENSE IN '||COUNTY_O||' WITH AT LEAST '||NUM||' VICTIMS.');
	END IF;
END;

/*LA PROCUDURA FREE_DATE RESTITUISCE LA PRIMA DATA DISPONIBILE
PER PROGRAMMARE UN'ESECUZIONE,(CONSIDERANDO CHE SI PUO' EFFETTUARE UN'UNICA ESECUZIONE AL GIORNO)
A PARTIRE DALLA DATA RICEVUTA IN INPUT.*/

CREATE OR REPLACE PROCEDURE FREE_DATE(DATE_CHECK IN OUT DATE) IS
 COUNTER NUMBER:=1;
 BEGIN
 LOOP
    SELECT COUNT(*) INTO COUNTER FROM SCHED_EXEC WHERE TRUNC(DATE_EXEC)=TRUNC(DATE_CHECK);
    EXIT WHEN COUNTER=0;
    DATE_CHECK:=DATE_CHECK+1;
 END LOOP;
 END;